# Generated by Django 3.2.8 on 2021-11-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_earn_from_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='package_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
