# Generated by Django 3.2.8 on 2021-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='threee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twoo',
            field=models.BooleanField(default=True),
        ),
    ]
