# Generated by Django 3.2.8 on 2021-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20211107_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='earn_from_ads',
            field=models.FloatField(default=0),
        ),
    ]
