# Generated by Django 3.2.8 on 2021-12-12 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_alter_profile_earn_from_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_by3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by3', to=settings.AUTH_USER_MODEL),
        ),
    ]
