# Generated by Django 3.2.8 on 2021-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211212_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eighthh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fivee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ninthh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seventhh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sixthh',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenthh',
            field=models.BooleanField(default=True),
        ),
    ]
