# Generated by Django 3.2.8 on 2021-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_recommended_by10'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datee',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
